title: Grant Geist
email: granthgeist@gmail.com
description: >- 
  Personal website of Grant Geist.
baseurl: "" # leave empty if hosting at root of domain
url: "https://grantgeist.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Site metadata
timezone: Europe/Berlin
permalink: /:categories/:title/
author: "Grant Geist"
social:
  name: "Grant Geist"
  links:
    - https://www.linkedin.com/in/grantgeist
    - https://x.com/grantgeist
# Default social/OG image
image: /assets/og/og-default.jpg

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - agents